import random, pyfiglet
from csv import reader
opened_file = open('words.csv')				#The word list is in a separeted file making it easier to be updated and managed
read_file = reader(opened_file)
word_list = list(read_file)
import subprocess

def art(art_num):					#ascii art that comes printed part by part at every wrong choice 
    art = ['                                                          ',
    '                                                          ',
    '                              ****************            ',
    '                              *              *            ',
    '                             ***             *            ',
    '                            *****            *            ',
    '                             ***             *            ',
    '                              *              *            ',
    '                        *************        *            ',
    '                             ***             *            ',
    '                             ***             *            ',
    '                             ***             *            ',
    '                             * *             *            ',
    '                             * *             *            ',
    '                             * *             *            ',
    '                             * *             *            ',
    '                                         *********        ',
    '                                         *********        ',
    '**********************************************************',
    '***   ***    ***    ***  ***   ******   ****  ****    ***    ***  ***',
    '***   ***   *****   ***  ***  ********  ****  ****   *****   ***  ***',
    '*********  *** ***  **** *** ***        ** ** * **  *** ***  **** ***',
    '********* ********* ** ***** ***  ***** ** ** * ** ********* ** *****',
    '***   ******** *******  ****  ********  **  **  ******* *******  ****',
    '***   *******   ******   ***   ******   **  **  ******   ******    **']

    for i in art[0:art_num]:
        print(i)

def error(x):						#The error function deals with the possible input mistakes made by the player

    tst_str = x.isdigit() 

    while tst_str is False: 
        x = input('Enter a valid option ')
        tst_str = x.isdigit()

    if tst_str is True:
        x = int(x)

    while x > 3:
        x = input('The options are [0] [1] [2] [3] ')
        tst_str = x.isdigit()

        while tst_str is False:
            x = input('Enter a valid option ')
            tst_str = x.isdigit()
        else:
            x = int(x)

    return x

def convert(x):						#The convert function makes a cleaner output

    d = []

    for i in x:
        char = str(i)
        d.append(char)
        e = ''. join(d)

    return e

def udrl(x):						#The udrl or underline function replaces with underlines the numbers of 
							#the list generated by "lenght = len(choice) trials = udrl(list(range(lenght)))"
    y = []

    for i in x:
        i = ' _ '
        y.append(i)

    return y

def hang_main(choice):					#The hang_main became a function to make it easier to loop and repeat the game

    lenght = len(choice)
    trials = udrl(list(range(lenght)))			#lenght = len(choice) & trials = udrl(list(range(lenght))) create the list at
    num = 0						#the same size of the random chose word, that will hold the inputed characters
    art_num = 4

    while art_num <= 30:				#The loop runs on the variable art_num, that is the same variable that increments
        guess = input('Enter a character ')		#to interact with the art() function to output the ascii art in seven parts
							#indicating the seven possible mistakes that can be made by the player
        for i in choice:
            if guess == i:
                trials[num] = guess			#The input is tested against each letter of the random word and if it is found
            num += 1					#to be matching it is placed in the same place and order of the original word
							#It is accomplished by increasing the index of the list trials for the number
        if guess not in choice:				#of letters of the random word in the for loop
            subprocess.call('clear')
            art(art_num)
            art_num += 4

        convtr = convert(trials)			#Cleaning the output from brackets, quotes and comas with convrt()

        if convtr == choice:				#The if statement compares the guessed word with the random one
            print(convtr)
            print('\nCongratulations!\n')
            break

        num = 0						#The variable num is set to 0, so the previus value is not carried the loop again

        print(convtr)
    print('\nThe answer is',choice)

banner = pyfiglet.figlet_format('Hangman')		#Figlet is used here to give a touch of style to the terminal game with
print(banner)						#the output of nice ascii art
print('\nLet\'s play hangman!\n')
print('\nCategories\n[0]Colors - [1]Cars\n[2]Cities - [3]People')
index = error(input('\nChoose one category from 0 to 3 '))

if index == 0:
    print("\nYou chose Colors\n")
elif index == 1:
    print('\nYou chose Cars\n')
elif index == 2:
    print('\nYou chose Cities\n')
elif index == 3:
    print('\nYou chose People\n')


word = []
for colunm in word_list[1:]:				# list[1:] list without header
    word.append(colunm[index])				# [0],[1],[2] or [3] chooses the category (see the word.csv)
    choice = random.choice(word)			# prints random word from the list word

hang_main(choice)

y = input('\nWould you like to play again?\nEnter [y] or [n] ')
while y == 'y':
    print('\nCategories\n[0]Colors - [1]Cars\n[2]Cities - [3]People')
    index = error(input('\nChoose one category from 0 to 3 '))
    if index == 0:
        print("\nYou chose Colors\n")
    elif index == 1:
        print('\nYou chose Cars\n')
    elif index == 2:
        print('\nYou chose Cities\n')
    elif index == 3:
        print('\nYou chose People\n')
    word = []
    for colunm in word_list[1:]:
        word.append(colunm[index])
        choice = random.choice(word)

    hang_main(choice)
    y = input('\nWould you like to play again?\nEnter [y] or [n] ')
else:
    print('\nThank\'s for playing!\n')
    banner2 = pyfiglet.figlet_format('Goodbye!')
    print(banner2)
